version: "3.9"

services:
  deploy-cmd:
    image: deploy-cmd-container
    container_name: deploy-cmd
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../test-deploy-commander/test.yml:/app/test.yml
      - /var/log/deploy:/app/log
    working_dir: /app
    tty: true
    stdin_open: true
    entrypoint: /bin/bash
