deployments:
- name: get-all-projects
  description: Получение всех репозиториев
  working_dir: /home/kolyan
  environment: null
  variables_file: null
  events:
  - name: pre-deploy
    description: Клонирование проектов
    commands:
    - command: sudo useradd -m {#name} && echo '{#name}:{passord}' | sudo chpasswd
      description: Создание пользователя
      ignore_errors: false
      rollback_command: null
      interactive: null
      inputs: null
      variables_file: null
    - command: echo 'Клонирование frontend'
      description: Клонирование frontend
      ignore_errors: true
      rollback_command: null
      interactive: null
      inputs: null
      variables_file: null
    - command: rm -rf /home/kolyan/me_best_practice || true
      description: Удаление старого репозитория frontend
      ignore_errors: true
      rollback_command: null
      interactive: null
      inputs: null
      variables_file: null
    - command: rm -rf /home/kolyan/advanced_todo_backend || true
      description: Удаление старого репозитория backend
      ignore_errors: true
      rollback_command: null
      interactive: null
      inputs: null
      variables_file: null
    - command: git clone https://gitlab.com/Nikolaikolya/me_best_practice.git
      description: Получение репозитория frontend
      ignore_errors: false
      rollback_command: rm -rf me_best_practice
      interactive: null
      inputs: null
      variables_file: null
    - command: echo 'Клонирование backend'
      description: Клонирование backend
      ignore_errors: true
      rollback_command: null
      interactive: null
      inputs: null
      variables_file: null
    - command: git clone https://gitlab.com/Nikolaikolya/advanced_todo_backend.git
      description: Получение репозитория backend
      ignore_errors: false
      rollback_command: rm -rf advanced_todo_backend
      interactive: null
      inputs: null
      variables_file: null
    fail_fast: true
- name: frontend-app
  description: Деплой фронтенд приложения
  working_dir: /home/kolyan/me_best_practice
  environment:
  - NODE_ENV=production
  - PORT=3000
  variables_file: null
  events:
  - name: pre-deploy
    description: Подготовка к деплою
    commands:
    - command: echo 'Начало деплоя frontend-app'
      description: Сообщение о начале деплоя
      ignore_errors: true
      rollback_command: null
      interactive: null
      inputs: null
      variables_file: null
    - command: git pull origin main
      description: Получение изменений из репозитория
      ignore_errors: null
      rollback_command: git reset --hard HEAD~1
      interactive: null
      inputs: null
      variables_file: null
    fail_fast: true
  - name: deploy
    description: Основной процесс деплоя
    commands:
    - command: docker build -t bp-app .
      description: Создание контейнера
      ignore_errors: null
      rollback_command: docker rmi bp-app || true
      interactive: null
      inputs: null
      variables_file: null
    - command: docker rm -f bp-container || true
      description: Удаление старого контейнера
      ignore_errors: true
      rollback_command: null
      interactive: null
      inputs: null
      variables_file: null
    - command: docker run -d --name bp-container -p 3000:3000 --restart always bp-app
      description: Запуск контейнера
      ignore_errors: null
      rollback_command: docker rm -f bp-container || true
      interactive: null
      inputs: null
      variables_file: null
    fail_fast: true
  - name: post-deploy
    description: Действия после деплоя
    commands:
    - command: rm -rf /home/kolyan/me_best_practice
      description: Удаление исходников
      ignore_errors: false
      rollback_command: null
      interactive: null
      inputs: null
      variables_file: null
    - command: echo 'Деплой frontend-app завершен'
      description: Сообщение о завершении деплоя
      ignore_errors: true
      rollback_command: null
      interactive: null
      inputs: null
      variables_file: null
    - command: curl -X POST https://api.telegram.org/bot<TOKEN>/sendMessage -d chat_id=<ID> -d text='Frontend успешно задеплоен'
      description: Уведомление об поднятии контейнера
      ignore_errors: true
      rollback_command: null
      interactive: null
      inputs: null
      variables_file: null
    fail_fast: false
- name: backend-api
  description: Деплой бэкенд API
  working_dir: /home/kolyan/advanced_todo_backend
  environment:
  - NODE_ENV=production
  - DB_HOST=localhost
  variables_file: null
  events:
  - name: deploy
    description: Основной процесс деплоя backend
    commands:
    - command: docker build -t at-server .
      description: Создание контейнера
      ignore_errors: null
      rollback_command: docker rmi at-server || true
      interactive: null
      inputs: null
      variables_file: null
    - command: docker rm -f at-server-container || true
      description: Удаление старого контейнера
      ignore_errors: true
      rollback_command: null
      interactive: null
      inputs: null
      variables_file: null
    - command: docker run -d --name at-server-container -p 4000:4000 --restart always at-server
      description: Запуск контейнера
      ignore_errors: null
      rollback_command: docker rm -f at-server-container || true
      interactive: null
      inputs: null
      variables_file: null
    fail_fast: true
  - name: post-deploy
    description: Действия после деплоя
    commands:
    - command: rm -rf /home/kolyan/advanced_todo_backend
      description: Удаление исходников
      ignore_errors: null
      rollback_command: null
      interactive: null
      inputs: null
      variables_file: null
    - command: echo 'Деплой backend-api завершен'
      description: Сообщение о завершении деплоя
      ignore_errors: true
      rollback_command: null
      interactive: null
      inputs: null
      variables_file: null
    fail_fast: null
- name: test-deploy
  description: Деплой test-deploy
  working_dir: /var/www/app
  environment:
  - NODE_ENV=production
  - PORT=3000
  variables_file: null
  events:
  - name: pre-deploy
    description: Команды перед деплоем
    commands:
    - command: echo 'Начало деплоя'
      description: Вывод сообщения о начале деплоя
      ignore_errors: true
      rollback_command: null
      interactive: false
      inputs: null
      variables_file: null
    fail_fast: true
  - name: deploy
    description: Основные команды деплоя
    commands:
    - command: git pull origin main
      description: Получение последних изменений из репозитория
      ignore_errors: null
      rollback_command: git reset --hard HEAD~1
      interactive: false
      inputs: null
      variables_file: null
    - command: npm ci
      description: Установка зависимостей
      ignore_errors: null
      rollback_command: null
      interactive: false
      inputs: null
      variables_file: null
    - command: npm run build
      description: Сборка проекта
      ignore_errors: null
      rollback_command: null
      interactive: false
      inputs: null
      variables_file: null
    fail_fast: true
  - name: post-deploy
    description: Команды после деплоя
    commands:
    - command: pm2 restart app
      description: Перезапуск приложения
      ignore_errors: null
      rollback_command: pm2 stop app
      interactive: false
      inputs: null
      variables_file: null
    - command: echo 'Деплой завершен'
      description: Вывод сообщения о завершении деплоя
      ignore_errors: true
      rollback_command: null
      interactive: false
      inputs: null
      variables_file: null
    fail_fast: false
variables_file: null
